apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dump-daily-summary
spec:
  schedule: '30 7 * * *'
  jobTemplate:
    metadata:
      name: dump-daily-summary
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: stockbot
              image: asia.gcr.io/riljian/stockbot
              command: ['/bin/sh', '-c']
              args:
                - |
                  python manage.py dump-daily-summary --exchange TWSE --date $(date +"%Y%m%d")
              env:
                - name: DB_HOST
                  value: mysql
                - name: DB_PORT
                  value: '3306'
                - name: DB_NAME
                  value: stockbot
                - name: DB_USER
                  value: stockbot
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: stockbot_password
