apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockbot
  labels:
    app: stockbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockbot
  template:
    metadata:
      labels:
        app: stockbot
    spec:
      containers:
        - name: stockbot
          image: asia.gcr.io/riljian/stockbot
          args: ['runserver', '0.0.0.0:8000']
          ports:
            - containerPort: 8000
              name: api
          resources:
            limits:
              cpu: '500m'
              memory: '1024Mi'
            requests:
              cpu: '10m'
              memory: '256Mi'
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: stockbot
            - name: DB_USER
              value: stockbot
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: stockbot_password
