apiVersion: batch/v1
kind: Job
metadata:
  name: stockbot-migrate
  labels:
    app: stockbot
spec:
  template:
    spec:
      containers:
        - name: stockbot
          image: asia.gcr.io/riljian/stockbot
          args: ['migrate']
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: stockbot
            - name: DB_USER
              value: stockbot
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: stockbot_password
            - name: BROKERAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: brokerage-account
                  key: key
            - name: BROKERAGE_ACCOUNT_IV
              valueFrom:
                secretKeyRef:
                  name: brokerage-account
                  key: iv
