# Generated by Django 3.1.3 on 2020-11-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('trade_volume', models.IntegerField(null=True)),
                ('transaction', models.IntegerField(null=True)),
                ('trade_value', models.BigIntegerField(null=True)),
                ('opening_price', models.FloatField(null=True)),
                ('highest_price', models.FloatField(null=True)),
                ('lowest_price', models.FloatField(null=True)),
                ('closing_price', models.FloatField(null=True)),
                ('last_best_bid_price', models.FloatField(null=True)),
                ('last_best_bid_volume', models.IntegerField(null=True)),
                ('last_best_ask_price', models.FloatField(null=True)),
                ('last_best_ask_volume', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('calendar_code', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255, null=True)),
                ('categories', models.ManyToManyField(related_name='stocks', to='stocks.StockCategory')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.exchange')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_exchange'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='stocks.stock'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('exchange', 'code'), name='unique_stock'),
        ),
    ]
