# Generated by Django 3.1.3 on 2021-01-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='brokerage_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='brokerage_user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
