# Generated by Django 3.1.6 on 2021-02-06 07:05

from django.db import migrations, models

from stocks.models import StockCategory


def adopt_new_category_field(apps, schema_editor):
    for category in StockCategory.objects.all():
        category.brokerage_code = category.name
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_fill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcategory',
            name='brokerage_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(adopt_new_category_field),
    ]
