# Generated by Django 3.1.6 on 2021-03-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20210305_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTestRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('no', models.UUIDField()),
                ('price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('ts', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.AddIndex(
            model_name='backtestrecord',
            index=models.Index(fields=['no'], name='stocks_back_no_70a5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrecord',
            index=models.Index(fields=['no', 'stock'], name='stocks_back_no_af0541_idx'),
        ),
    ]
