# Generated by Django 3.1.6 on 2021-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20210305_0027'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tick',
            constraint=models.UniqueConstraint(fields=('stock', 'ts'), name='unique_tick'),
        ),
    ]
