# Generated by Django 3.1.6 on 2021-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20210306_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='foreign_dealer_buy_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='foreign_dealer_sell_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='investment_trust_buy_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='investment_trust_sell_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='local_dealer_hedge_buy_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='local_dealer_hedge_sell_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='local_dealer_proprietary_buy_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='local_dealer_proprietary_sell_volume',
            field=models.IntegerField(null=True),
        ),
    ]
