# Generated by Django 3.1.6 on 2021-03-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_fill_investor_summary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='backtestrecord',
            name='stocks_back_no_70a5f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='backtestrecord',
            name='stocks_back_no_af0541_idx',
        ),
        migrations.RemoveField(
            model_name='backtestrecord',
            name='no',
        ),
        migrations.AddField(
            model_name='backtestrecord',
            name='commit',
            field=models.CharField(default='3558f241fecf8eb63681ddb3421e2e4aa174ba38', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='backtestrecord',
            index=models.Index(fields=['commit'], name='stocks_back_commit_2d4ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrecord',
            index=models.Index(fields=['commit', 'stock'], name='stocks_back_commit_3f28f9_idx'),
        ),
    ]
