# Generated by Django 3.1.6 on 2021-04-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_auto_20210330_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservativeStrategyTestRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('highest_in_30_days', models.FloatField()),
                ('investors', models.CharField(max_length=255)),
                ('continuous_days', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservative_candidates', to='stocks.stock')),
            ],
        ),
    ]
