name: Release

on:
  release:
    types: [created]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  K8S_CLUSTER: ${{ secrets.K8S_CLUSTER }}
  CONTAINER_REGISTRY: asia.gcr.io
  IMAGE: stockbot

jobs:
  build-publish:
    name: Build, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper for authentication
        run: |-
          gcloud --quiet auth configure-docker "$CONTAINER_REGISTRY"
          gcloud --quiet container clusters get-credentials "$K8S_CLUSTER"

      - name: Get the image version
        run: echo "IMAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build
        run: |-
          docker build \
            --tag "$CONTAINER_REGISTRY/$PROJECT_ID/$IMAGE:$IMAGE_VERSION" \
            --build-arg COMMIT_SHA="$GITHUB_SHA" \
            .

      - name: Publish
        run: |-
          docker push "$CONTAINER_REGISTRY/$PROJECT_ID/$IMAGE:$IMAGE_VERSION"

      - name: Deploy
        run: |-
          kubectl set image deployments.apps/stockbot stockbot=$CONTAINER_REGISTRY/$PROJECT_ID/$IMAGE:$IMAGE_VERSION
          kubectl set image cronjobs.batch/dump-daily-summary stockbot=$CONTAINER_REGISTRY/$PROJECT_ID/$IMAGE:$IMAGE_VERSION
